@startuml

' =========================
' ENUM
' =========================
enum Test {
    TEST2
    TEST2
}

enum OrderType {
    EAT_IN
    DELIVERY
}

' =========================
' CLASSES
' =========================
class Customer {
    +id: int
    +name: String
    +phone: String
    +createOrder(): Order
    +signin(): void
    +signup():void
    +makePayment(): void
    +trackOrder(): Order
    +cancelOrder(): void
}

class Restaurant {
    +id: int
    +name: String
    +address: String
    +getOrders(): Order[]
}

class Order {
    +id: int
    +orderDate: Date
    +type: OrderType
    +addItem(): void
    +totalPrice(): double
    +attachPayment(): void
    +attachDeliveryInfo(): void
}

class DeliveryInfo {
    +address: String
    +receiverName: String
    +phone: String
}

class Payment {
    +amount: double
    +timestamp: Date
    +verifyPayment(): boolean
    +pay()
}

class CashPayment {
}

class CardPayment {
    +cardNumber: String
}

class EWalletPayment {
    +walletType: String
}

class Menu {
    +id: int
    +title: String
    +addItem(): void
    +getItems(): MenuItem[]
}

class MenuItem {
    +id: int
    +name: String
    +price: double
}

class OrderItem {
    +quantity: int
    +subtotal(): double
}


' =========================
' RELATIONSHIPS
' =========================

' --- Association ---
Customer "1" --> "0..*" Order
Restaurant "1" --> "0..*" Order
Order "1" --> "1" Payment

' --- Composition ---
Order "1" -- "1.." OrderItem
Order "1" *-- "0..1" DeliveryInfo

' --- Aggregation ---
Menu "1" o-- "1..*" MenuItem

' --- Inheritance ---
Payment <|-- CashPayment
Payment <|-- CardPayment
Payment <|-- EWalletPayment

@enduml